// svelte/src/App.svelte
<script lang="ts">
    import {themeClass} from 'vanilla'
    import Button from './Button.svelte'

    let danger = true

    function setDanger() {
        danger = !danger
    }
</script>

<main class={themeClass}>
    <Button handler={setDanger}
            variant={{type: danger ? 'danger' : 'okay', border: 'some', size: 'small'}}
            text={danger ? "I'm in danger" : "I'm okay!"}
    />
</main>

// react/App.tsx
import {themeClass} from "vanilla"
import {useState} from "react"
import {ButtonComponent} from "./Button"

const App = () => {
    const [danger, setDanger] = useState(true)

    return (
        <div className={themeClass}>
            <ButtonComponent
                handler={() => setDanger(!danger)}
                text={danger ? "I'm in danger" : "I'm okay!"}
                variant={{type: danger ? 'danger' : 'okay', border: 'some', size: 'small'}}
            />
        </div>
    )
}

export default App
