// react/App.tsx
import {box} from "vanilla"
import {useState} from "react"
import {ButtonComponent} from "./Button"

const App = () => {
    const [danger, setDanger] = useState(true)

    return (
        <div className={box({type: 'center', border: 'some'})}>
            <ButtonComponent
                handler={() => setDanger(!danger)}
                text={danger ? "I'm in danger" : "I'm okay!"}
                variant={{type: danger ? 'danger' : 'okay', border: 'some', size: 'small'}}
            />
        </div>
    )
}

export default App

// vue/App.vue
<script setup lang="ts">
import {box} from "vanilla"
import ButtonComponent from "./ButtonComponent.vue"
import {ref} from "vue"

const danger = ref(true)

const setDanger = () => {
  danger.value = !danger.value
}
</script>

<template>
  <div :class="box({type: 'center', border: 'some'})">
    <h2>Vue.js</h2>
    <ButtonComponent
        :handler="setDanger"
        :variant="{type:  danger ? 'danger' : 'okay', border: 'some', size: 'small'}"
        text="I'm in danger"
    />
  </div>
</template>
